function [chi_predict] = UKF_GenerateTheSigmaPoints2L1(...
    x_predict,...
    sqrtP_predict, ...
    sqrtLPlusLAmbda,...
    UKF_L)
chi_predict = ...
    [...
    x_predict, ...
    x_predict * ones(1, UKF_L) + sqrtLPlusLAmbda * sqrtP_predict,...
    x_predict * ones(1, UKF_L) - sqrtLPlusLAmbda * sqrtP_predict...
    ];

end